#handlers

---
handlers:
-
    handler: bitfield
    url: https://bitfieldconsulting.com/golang
-
    handler: threedotslabs
    url: https://threedots.tech/
-
    handler: hashnode
    url: https://hashnode.com/n/go
